version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            cd project_management_app
            docker build -t $DOCKER_USERNAME/todolist .
      - run:
          name: Log in to DockerHub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command: |
            docker push $DOCKER_USERNAME/todolist

  deploy:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
    steps:
      - run:
          name: Deploy to EC2
          command: ./deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
