version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
    steps:
      - checkout
      - run: docker build -t $DOCKER_USERNAME/todolist .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker push $DOCKER_USERNAME/todolist

  deploy:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
    steps:
      - run: ./deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
