    - image: circleci/ruby:2.7.1-node-browsers
    steps:
      - checkout
      - run: echo "hello"
      - run: docker build -t $DOCKER_USERNAME/todolist .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker push $DOCKER_USERNAME/todolist

  deploy:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
    steps:
      - run: echo "world"
      - run: ./deploy.sh

workflows:
  version: 2
  test_and_deploy:
  build_and_deploy:
    jobs:
      - build
      - deploy: